name: Runs dependency installs and ad hoc build on ephemeral gh runners

on: [push]

jobs:
  list-s3:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    environment: public 
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          # Use OpenID Connect (OIDC) for enhanced security (recommended)
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NAME }}:role/spot_instance_role
          aws-region: us-east-1

      - name: Install Python and Dependencies
        run: |
             if ! command -v pip3 &> /dev/null
             then
                echo "pip3 not found, installing..."
                sudo dnf install python pip -y
                pip install boto3 requests 
             else
                echo "pip3 is already installed, continuing..."
                pip install boto3 requests
             fi
             

      - name: Run Python shell commands to check for S3 bucket via boto3
        shell: python
        run:  |
          import os; import boto3; import botocore.exceptions; bucket_name = os.getenv("S3_BUCKET_NAME"); s3 = boto3.client("s3"); print(f"Bucket '{bucket_name}' exists") if s3.head_bucket(Bucket=bucket_name) else print(f"Bucket '{bucket_name}' does not exist") if not isinstance(e := None, botocore.exceptions.ClientError) or e.response["Error"]["Code"] != "404" else None;
        env:
          S3_BUCKET_NAME: win11-tlc


