name: Runs dependency installs and test script on dynamically provisioned gh runners
# v1
on: [push]

jobs:
  complete-lifecycle:
    #runs-on: ubuntu-latest # For GH Runners, not self-hosted
    runs-on: self-hosted
    continue-on-error: true # ALL jobs need this to reach runner hook's lifecycle
    environment: public 
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read
    steps:
## The id-token above plus the commented steps below gives GH actions
## the creds to do AWS stuff using any runner, with or without TLC
## Terraform (tf-files) or whether it is self-hosted or not.
## However, when provisioning the gh runner with tf-files,
## you do not need the aws-actions module because we already 
## attached the 'spot_instance_role' via the runner's instance profile.
#      - name: Checkout repository
#        uses: actions/checkout@v4
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v5
#        with:
#          # Use an AWS role in your account with suitable permissions, if not the one below
#          # Manually enter the ACCOUNT_ID value in GH Secrets or update in tf-files/main.tf
#          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/spot_instance_role
#          aws-region: us-east-1

      - name: Install Dependencies Required to Complete Dynamic Provisioning Lifecycle
        run: |
             if ! command /home/gh-runner/bin/aws --version  &> /dev/null
             then
                cd /home/gh-runner/          
                curl  -o awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
                python -m zipfile -e awscliv2.zip .
                chmod 755 /home/gh-runner/aws/dist/aws
                # To disable (ie break) automatic instance termination in 
                # the instance lifecycle, change '-b ~/bin' to another PATH
                bash ./aws/install -i ~/aws-cli -b ~/bin
                chmod 755 /home/gh-runner/block/aws
                /home/gh-runner/bin/aws --version
                env
             else
                echo "AWS CLI is already installed, printing AWSCLI version and env vars..."
                /home/gh-runner/bin/aws --version
             fi
#  Replace the step below with the step(s) in your actual workflow
      - name: Run Python shell commands to check os and node name, then sleep 3 seconds
        shell: python
        run:  |
           import platform; import time; print(platform.platform()); print(platform.node()); time.sleep(3);
      - name: Run bash shell and print a command out
        shell: bash
        run:  |
               date
               curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x ./kubectl && mkdir -p ~/.local/bin && mv ./kubectl ~/.local/bin/kubectl && ~/.local/bin/kubectl version --client
               
               curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_ENABLE=true INSTALL_K3S_SKIP_START=true K3S_TOKEN="${k3s_token}" sh - && k3s server --rootless
               # Check for Ready node, takes ~30 seconds 
               sleep 30
               KUBECONFIG=~/.kube/k3s.yaml ~/.local/bin/kubectl get node 
               
#  Lifecycle termination of node at job completion is an 'adminstrator' function controlled
#  via ACTIONS_RUNNER_HOOK_JOB_COMPLETED and not available to workflows for 'security reasons' 
